# https://circleci.com/orbs/registry/licensing for details. 
version: 2.1
description: Orb for firebase deploy.
orbs:
  firebase-deploy: cloudliner/firebase-deploy@0.0.2
jobs:
  build_and_test: 
    working_directory: ~/nuxt-firebase-todo
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: 
            npm install 
            npm rebuild
      - save_cache: # special step to save the dependency cache
          key: dependency-cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build-nuxt-app
          command: |
            npm run build
            npm run generate
      - persist_to_workspace:
          root: ~/nuxt-firebase-todo
          paths:
            - dist/*
      - run: # run tests
          name: test
          command: npm run test
      - store_artifacts: # special step to save test results as as artifact
          # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/ 
          path: test/results/test_result.json
          prefix: tests
  deploy:
    working_directory: ~/nuxt-firebase-todo
    docker:
      - image: circleci/node:latest
    parameters:
      token:
        type: string
        default: "${FIREBASE_TOKEN}"
        description: Firebase Deploy Token
    steps:
      - checkout
      - attach_workspace:
          at: ~/nuxt-firebase-todo
      - run:
          name: Install Firebase Tools
          command: npm install --prefix=./firebase-deploy firebase-tools
      - run:
          name: Deploy to Firebase
          command: |
            echo "${FIREBASE_TOKEN}"
            echo <<parameters.token>>
            ./firebase-deploy/node_modules/.bin/firebase deploy --token=<<parameters.token>>

workflows: 
  version: 2.1
  build_and_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test
          filters:
            branches:
              only: master
